# Generated by Django 5.2.17 on 2026-09-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_promote_dev_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', '구매자'), ('creator', '크리에이터'), ('vendor', '벤더'), ('admin', '관리자')], default='buyer', max_length=10),
        ),
    ]
