# Generated by Django 5.2.17 on 2026-09-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('stock', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('selling', '판매중'), ('sold_out', '품절'), ('inactive', '비활성')], default='selling', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='vendors.vendorprofile')),
            ],
        ),
    ]
