# Generated by Django 5.2.17 on 2026-09-14 01:36

from django.db import migrations

CATEGORY_NAMES = ["테크", "뷰티", "리빙"]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    for name in CATEGORY_NAMES:
        Category.objects.get_or_create(name=name)


def remove_categories(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Category.objects.filter(name__in=CATEGORY_NAMES, parent__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
