# Generated by Django 5.2.17 on 2026-09-14 02:37

from django.db import migrations

VENDORS = [
    {"name": "OO전자", "business_no": "111-11-11111", "contact": "vendor1@example.com",
     "settlement_account": "국민 111-111-111111"},
    {"name": "OO코스메틱", "business_no": "222-22-22222", "contact": "vendor2@example.com",
     "settlement_account": "국민 222-222-222222"},
    {"name": "OO리빙", "business_no": "333-33-33333", "contact": "vendor3@example.com",
     "settlement_account": "국민 333-333-333333"},
]

PRODUCTS = [
    {"vendor": "OO전자", "category": "테크", "name": "무선 이어폰", "price": 39000,
     "commission_rate": "5.00", "description": "가볍고 오래 쓰는 무선 이어폰. 한 번 충전으로 최대 8시간 재생.",
     "options": {"색상": ["블랙", "화이트"]}, "stock": {"블랙": 30, "화이트": 30}},
    {"vendor": "OO전자", "category": "테크", "name": "보조배터리", "price": 29000,
     "commission_rate": "5.00", "description": "얇고 가벼운데 20000mAh, 고속충전 지원.",
     "options": {}, "stock": {"기본": 50}},
    {"vendor": "OO전자", "category": "테크", "name": "무선 충전기", "price": 21000,
     "commission_rate": "4.00", "description": "거치형 3in1 무선 충전기, 폰·워치·이어폰 동시 충전.",
     "options": {}, "stock": {"기본": 40}},
    {"vendor": "OO코스메틱", "category": "뷰티", "name": "저자극 선크림", "price": 18000,
     "commission_rate": "8.00", "description": "민감성 피부도 편하게 쓰는 저자극 선크림, SPF50+.",
     "options": {}, "stock": {"기본": 60}},
    {"vendor": "OO코스메틱", "category": "뷰티", "name": "수분크림", "price": 22000,
     "commission_rate": "8.00", "description": "건조한 겨울철에도 촉촉한 고보습 수분크림.",
     "options": {}, "stock": {"기본": 45}},
    {"vendor": "OO코스메틱", "category": "뷰티", "name": "클렌징 오일", "price": 24000,
     "commission_rate": "7.00", "description": "메이크업까지 깔끔하게 지우는 순한 클렌징 오일.",
     "options": {}, "stock": {"기본": 35}},
    {"vendor": "OO리빙", "category": "리빙", "name": "미니 가습기", "price": 25000,
     "commission_rate": "6.00", "description": "책상 위에 딱 맞는 사이즈의 미니 가습기.",
     "options": {"색상": ["화이트", "그레이"]}, "stock": {"화이트": 20, "그레이": 20}},
    {"vendor": "OO리빙", "category": "리빙", "name": "극세사 러그", "price": 32000,
     "commission_rate": "6.00", "description": "발이 폭 감기는 극세사 러그, 100x150cm.",
     "options": {"색상": ["아이보리", "그레이"]}, "stock": {"아이보리": 15, "그레이": 15}},
    {"vendor": "OO리빙", "category": "리빙", "name": "무드등", "price": 19000,
     "commission_rate": "6.00", "description": "은은한 분위기를 만들어주는 터치 무드등.",
     "options": {}, "stock": {"기본": 25}},
]


def seed_products(apps, schema_editor):
    VendorProfile = apps.get_model("vendors", "VendorProfile")
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    vendors_by_name = {}
    for data in VENDORS:
        vendor, _ = VendorProfile.objects.get_or_create(
            name=data["name"],
            defaults={
                "business_no": data["business_no"],
                "contact": data["contact"],
                "settlement_account": data["settlement_account"],
                "status": "approved",
            },
        )
        vendors_by_name[data["name"]] = vendor

    categories_by_name = {c.name: c for c in Category.objects.filter(parent__isnull=True)}

    for data in PRODUCTS:
        Product.objects.get_or_create(
            name=data["name"],
            defaults={
                "vendor": vendors_by_name[data["vendor"]],
                "category": categories_by_name[data["category"]],
                "description": data["description"],
                "price": data["price"],
                "commission_rate": data["commission_rate"],
                "options": data["options"],
                "stock": data["stock"],
                "status": "selling",
            },
        )


def remove_products(apps, schema_editor):
    VendorProfile = apps.get_model("vendors", "VendorProfile")
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(name__in=[p["name"] for p in PRODUCTS]).delete()
    VendorProfile.objects.filter(name__in=[v["name"] for v in VENDORS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_categories'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_products, remove_products),
    ]
