"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 로컬 개발 기본값은 예전부터 쓰던 dev 키 그대로 두되(이미 git 이력에 노출돼 있어 더 숨길 의미가
# 없음), 실제 배포 시엔 .env에 새로 생성한 값을 넣어서 이 기본값을 쓰지 않게 한다 → ADR-040 참고.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-=lvlbt+q*t598z#wah)i(7um6hhmvt&#uk0rp63n0na@e!wbcd'
)

# SECURITY WARNING: don't run with debug turned on in production!
# 배포 전엔 DEBUG=True/ALLOWED_HOSTS=[]가 하드코딩돼 있어서, 배포 가이드대로 DEBUG를 끄면 그 즉시
# ALLOWED_HOSTS가 비어있어 모든 요청이 400으로 막히는 상태였음(통합 테스트 중 발견) → ADR-040 참고.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'vendors',
    'catalog',
    'recommendations',
    'orders',
    'payments',
    'settlements',
    'adminconsole',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Next.js 프론트(로컬 3000번 포트, 배포 시엔 실제 도메인/IP)에서 세션 쿠키를 실어 API를 호출할 수
# 있게 허용(ADR-011: 인증 방식은 세션 쿠키). 예전엔 localhost:3000으로 하드코딩돼 있어서 배포된
# 프론트 주소에서 오는 요청은 전부 CORS로 막히는 상태였음 → ADR-040 참고.
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',') if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Django의 CSRF 보호는 CORS와 별개로 요청의 Origin이 신뢰할 수 있는 곳인지도 검사한다.
# 프론트(3000)와 백엔드(8000)가 포트가 달라 별도 출처로 취급되므로 명시적으로 등록해야 함.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(',') if o.strip()
]

AUTH_USER_MODEL = 'accounts.User'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# docker-compose.yml의 postgres 서비스와 값이 맞아야 함. Docker 설치 전까지는 실제로 연결되지 않음.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'creamo'),
        'USER': os.environ.get('POSTGRES_USER', 'creamo'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'creamo'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 상품 썸네일 등 사용자가 업로드하는 파일. backend/ 전체가 docker-compose에서 볼륨 마운트되어 있어서
# media/에 저장된 파일은 컨테이너를 내렸다 올려도 호스트 디스크에 그대로 남는다.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 포트원(PortOne) V2 결제 연동. 값은 루트 .env(git에 안 올라감)에서 docker-compose를 거쳐 들어옴
# → ADR-036 참고. STORE_ID/CHANNEL_KEY는 공개 식별자(프론트에도 노출됨)지만 API_SECRET은 서버
# 전용 비밀 키이므로 여기서만 사용한다.
PORTONE_STORE_ID = os.environ.get('PORTONE_STORE_ID', '')
PORTONE_CHANNEL_KEY = os.environ.get('PORTONE_CHANNEL_KEY', '')
PORTONE_API_SECRET = os.environ.get('PORTONE_API_SECRET', '')

# 회원가입 이메일 인증 발송용 SMTP. 값은 루트 .env에서 docker-compose를 거쳐 들어옴 → ADR-039 참고.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Redis 연결 정보. 이번 이메일 인증 기능 전에는 docker-compose에만 떠 있고 실제로 쓰는 코드가
# 없었음(ADR-039 참고) — accounts/verification.py에서 이메일 인증코드 저장·조회에 사용.
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', '6379'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
