# Generated by Django 5.2.17 on 2026-09-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_demo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', '결제대기'), ('paid', '결제완료'), ('preparing', '상품준비'), ('shipping', '배송중'), ('delivered', '배송완료'), ('cancelled', '취소됨')], default='pending', max_length=10),
        ),
    ]
