# Generated by Django 5.2.17 on 2026-09-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
