# Generated by Django 5.2.17 on 2026-09-21 15:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_address_alter_order_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='전화번호 형식이 올바르지 않습니다. 예: 010-1234-5678', regex='^0\\d{1,2}-?\\d{3,4}-?\\d{4}$')]),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('phone__regex', '^0\\d{1,2}-?\\d{3,4}-?\\d{4}$')), name='order_phone_format'),
        ),
    ]
