# Generated by Django 5.2.17 on 2026-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorrecommendation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', '제안됨'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=10),
        ),
    ]
