from django.urls import path

from .views import (
    CheckEmailView,
    CreatorDashboardProductsView,
    CreatorDashboardStatsView,
    CreatorDetailView,
    CreatorListView,
    CreatorProductsView,
    CreatorProfileCreateView,
    CreatorRecommendationRequestsView,
    CreatorRecommendationRespondView,
    CreatorSettlementsView,
    CsrfView,
    LoginView,
    LogoutView,
    MeView,
    SendVerificationCodeView,
    SignupView,
    VendorOrderItemsView,
    VendorOrderItemStatusView,
    VendorProductDetailView,
    VendorProductsView,
    VendorProductStatusView,
    VendorProfileCreateView,
    VendorRecommendationsView,
    VendorSettlementGenerateView,
    VendorSettlementsView,
    VerifyCodeView,
)

urlpatterns = [
    path("auth/csrf", CsrfView.as_view()),
    path("auth/check-email", CheckEmailView.as_view()),
    path("auth/send-verification-code", SendVerificationCodeView.as_view()),
    path("auth/verify-code", VerifyCodeView.as_view()),
    path("auth/signup", SignupView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/me", MeView.as_view()),
    path("creator/profile", CreatorProfileCreateView.as_view()),
    path("creator/dashboard/stats", CreatorDashboardStatsView.as_view()),
    path("creator/dashboard/products", CreatorDashboardProductsView.as_view()),
    path("creator/dashboard/requests", CreatorRecommendationRequestsView.as_view()),
    path("creator/dashboard/requests/<int:pk>/respond", CreatorRecommendationRespondView.as_view()),
    path("creator/dashboard/settlements", CreatorSettlementsView.as_view()),
    path("creators", CreatorListView.as_view()),
    path("creators/<int:pk>", CreatorDetailView.as_view()),
    path("creators/<int:pk>/products", CreatorProductsView.as_view()),
    path("vendor/profile", VendorProfileCreateView.as_view()),
    path("vendor/products", VendorProductsView.as_view()),
    path("vendor/products/<int:pk>", VendorProductDetailView.as_view()),
    path("vendor/products/<int:pk>/status", VendorProductStatusView.as_view()),
    path("vendor/products/<int:pk>/recommendations", VendorRecommendationsView.as_view()),
    path(
        "vendor/products/<int:pk>/recommendations/<int:creator_id>",
        VendorRecommendationsView.as_view(),
    ),
    path("vendor/settlements", VendorSettlementsView.as_view()),
    path("vendor/settlements/generate", VendorSettlementGenerateView.as_view()),
    path("vendor/order-items", VendorOrderItemsView.as_view()),
    path("vendor/order-items/<int:pk>/status", VendorOrderItemStatusView.as_view()),
]
