# Generated by Django 5.2.17 on 2026-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_no', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=100)),
                ('settlement_account', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '승인대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=10)),
            ],
        ),
    ]
