# Generated by Django 5.2.17 on 2026-09-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_transaction_id', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
