# Generated by Django 5.2.17 on 2026-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('vendor', '벤더'), ('creator', '크리에이터')], max_length=10)),
                ('target_id', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('completed', '완료')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
